force-app/main/default/objects/Internship__c/Internship__c.object-meta.xml
<CustomObject>
    <label>Internship</label>
    <nameField>
        <label>Internship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <color>#009900</color>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <color>#FF0000</color>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Selected</fullName>
                <isActive>false</isActive>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Viewed</fullName>
                <isActive>false</isActive>
                <label>Viewed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internship_Application__c/Internship_Application__c.object-meta.xml
<CustomObject>
    <label>Internship Application</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Internship Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internship Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internship_Application__c/fields/Internship__c.field-meta.xml
<CustomField>
    <fullName>Internship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internship</label>
    <referenceTo>Internship__c</referenceTo>
    <relationshipLabel>Internship Applications</relationshipLabel>
    <relationshipName>Internship_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internship_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Personal Interview</fullName>
                <isActive>false</isActive>
                <label>Personal Interview</label>
            </value>
            <value>
                <fullName>Review Resume</fullName>
                <isActive>false</isActive>
                <label>Review Resume</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ObjectDetailController.cls
public with sharing class ObjectDetailController {
    @AuraEnabled(cacheable=true)
    public static List<Internship_Application__c> getObjectDetails() {
        
        Id loggedInUserId = UserInfo.getUserId();
List<Internship_Application__c> internshipApplications = [SELECT Id, Status__c, Internship__r.Name FROM Internship_Application__c WHERE Internship__r.Name!=NULL AND  OwnerId = :loggedInUserId];
return internshipApplications;
      
    }
}