force-app/main/default/objects/Internship__c/Internship__c.object-meta.xml
<CustomObject>
    <label>Internship</label>
    <nameField>
        <label>Internship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internship__c/fields/InternshipEndDate__c.field-meta.xml
<CustomField>
    <fullName>InternshipEndDate__c</fullName>
    <label>InternshipEndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Internship__c/fields/InternshipStartDate__c.field-meta.xml
<CustomField>
    <fullName>InternshipStartDate__c</fullName>
    <label>InternshipStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/InternshipController.cls
public class InternshipController {
    @AuraEnabled
    public static List<Internship__c> getInterships() {
        // Query data from the Internship__c object
        List<Internship__c> internships = [SELECT Id, Name, InternshipStartDate__c, InternshipEndDate__c FROM Internship__c where InternshipStartDate__c!=null AND InternshipEndDate__c!=null];
      //iam commiting these
return internships;
    }
}