force-app/main/default/objects/Internship__c/Internship__c.object-meta.xml
<CustomObject>
    <label>Internship</label>
    <nameField>
        <label>Internship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internship__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>for getting the notifications related applicants</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Internship__c/fields/InternshipApplicationDeadline__c.field-meta.xml
<CustomField>
    <fullName>InternshipApplicationDeadline__c</fullName>
    <label>InternshipApplicationDeadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Internship__c/fields/InternshipEndDate__c.field-meta.xml
<CustomField>
    <fullName>InternshipEndDate__c</fullName>
    <label>InternshipEndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Internship__c/fields/InternshipLevel__c.field-meta.xml
<CustomField>
    <fullName>InternshipLevel__c</fullName>
    <label>InternshipLevel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>WorkingArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Easy E1</fullName>
            </value>
            <value>
                <fullName>Easy E2</fullName>
            </value>
            <value>
                <fullName>Easy E3</fullName>
            </value>
            <value>
                <fullName>Easy E4</fullName>
            </value>
            <value>
                <fullName>Easy E5</fullName>
            </value>
            <value>
                <fullName>Intermediate I1</fullName>
            </value>
            <value>
                <fullName>Intermediate I2</fullName>
            </value>
            <value>
                <fullName>Intermediate I3</fullName>
            </value>
            <value>
                <fullName>Intermediate I4</fullName>
            </value>
            <value>
                <fullName>Intermediate I5</fullName>
            </value>
            <value>
                <fullName>Hard H1</fullName>
            </value>
            <value>
                <fullName>Hard H2</fullName>
            </value>
            <value>
                <fullName>Hard H3</fullName>
            </value>
            <value>
                <fullName>Hard H4</fullName>
            </value>
            <value>
                <fullName>Hard H5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internship__c/fields/InternshipStartDate__c.field-meta.xml
<CustomField>
    <fullName>InternshipStartDate__c</fullName>
    <label>InternshipStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Internship__c/fields/Opennings__c.field-meta.xml
<CustomField>
    <fullName>Opennings__c</fullName>
    <label>Opennings Left</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Internship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <color>#009900</color>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <color>#FF0000</color>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Selected</fullName>
                <isActive>false</isActive>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Viewed</fullName>
                <isActive>false</isActive>
                <label>Viewed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internship__c/fields/WorkingArea__c.field-meta.xml
<CustomField>
    <fullName>WorkingArea__c</fullName>
    <label>WorkingArea</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Chorus</fullName>
            </value>
            <value>
                <fullName>Freshers</fullName>
            </value>
            <value>
                <fullName>Lab</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Paper Publication</fullName>
            </value>
            <value>
                <fullName>Printing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internship_Application__c/Internship_Application__c.object-meta.xml
<CustomObject>
    <label>Internship Application</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Internship Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internship Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internship_Application__c/fields/CandEmail__c.field-meta.xml
<CustomField>
    <fullName>CandEmail__c</fullName>
    <defaultValue>$User.Email</defaultValue>
    <externalId>true</externalId>
    <label>CandEmail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Internship_Application__c/fields/Internship__c.field-meta.xml
<CustomField>
    <fullName>Internship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internship</label>
    <referenceTo>Internship__c</referenceTo>
    <relationshipLabel>Internship Applications</relationshipLabel>
    <relationshipName>Internship_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internship_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Personal Interview</fullName>
                <isActive>false</isActive>
                <label>Personal Interview</label>
            </value>
            <value>
                <fullName>Review Resume</fullName>
                <isActive>false</isActive>
                <label>Review Resume</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InternshipApplicationTriggerTest.cls
@isTest
public class InternshipApplicationTriggerTest {
    public static void runtheMethods(){
        testApplyWithOpennings_Greater_Than_0_And_New_Staus_Application();
        testApplyWithOpennings_Greater_Than_0_And_Hired_Staus_Application();
        testApplyWithOpennings_Greater_Than_0_And_Rejected_Staus_Application();
        testApplyWithOpennings_Greater_Less_Than_0_And_New_Staus_Application();
        
    }
static Date d = Date.today();


    static Internship__c testInternship = new Internship__c(
    Name = 'TestSoftwareDeveloper',
    Status__c='Opened',
    Opennings__c = 0,
    WorkingArea__c = 'Chorus',
    InternshipLevel__c = 'Hard H1',
    Email__c = 'gyaneshjha4@gmail.com',
    InternshipStartDate__c = d.addDays(10),  
    InternshipApplicationDeadline__c = d.addDays(2),  
    InternshipEndDate__c = d.addDays(30) 
    );
//--------------------------------------------------------------------------------------------------------------------------------------
    static Internship_Application__c hiredApplication = new Internship_Application__c(
            Status__c = 'New',
            CandEmail__c = 'test@example01.com',
            Internship__c = testInternship.Id);
        
static testMethod void testApplyWithOpennings_Greater_Than_0_And_New_Staus_Application() {
    
   
    insert testInternship;
    
       
    hiredApplication.Status__c='Hired';
    try{
        update hiredApplication;
        System.debug('The Intern is Hired --testApplyWithOpennings_Greater_Than_0_And_New_Staus_Application');
    }catch(DmlException e){
        System.debug('Something error in this --testApplyWithOpennings_Greater_Than_0_And_New_Staus_Application');
    }
}
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    static testMethod void testApplyWithOpennings_Greater_Than_0_And_Hired_Staus_Application() {
        
    insert testInternship;
    
        
    hiredApplication.Status__c='Hired';
    try{
        update hiredApplication;
                System.debug('Something error in this --testApplyWithOpennings_Greater_Than_0_And_Hired_Staus_Application');
    }catch(DmlException e){
        System.debug('Sorry, The Interns is already Hired --testApplyWithOpennings_Greater_Than_0_And_Hired_Staus_Application');

    }
}
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
     static testMethod void testApplyWithOpennings_Greater_Than_0_And_Rejected_Staus_Application() {
    insert testInternship;
    
       
    hiredApplication.Status__c='Rejected';
    try{
        update hiredApplication;
     System.debug('The Interns is Rejected and opennings are available now fot this position--testApplyWithOpennings_Greater_Than_0_And_Rejected_Staus_Application');
    }catch(DmlException e){
               System.debug('Something error in this --testApplyWithOpennings_Greater_Than_0_And_Rejected_Staus_Application');
    
    }
}
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    static testMethod void testApplyWithOpennings_Greater_Less_Than_0_And_New_Staus_Application() {
    insert testInternship;
        testInternship.Opennings__c=0;
        update testInternship;
    
        
    hiredApplication.Status__c='Hired';
    try{
        update hiredApplication;
        System.debug('Something error in this --testApplyWithOpennings_Greater_Than_0_And_Hired_Staus_Application');
    }catch(DmlException e){

                System.debug('Opennings is closed for this positions --testApplyWithOpennings_Greater_Than_0_And_Hired_Staus_Application');
    }
}
}