force-app/main/default/objects/CQ_GJ_SQX_Child_Object__c/CQ_GJ_SQX_Child_Object__c.object-meta.xml
<CustomObject>
    <label>CQ GJ Child Object</label>
    <nameField>
        <label>Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CQ GJ Child Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CQ_GJ_SQX_Child_Object__c/fields/CQ_GJ_SQX_Parent_Info__c.field-meta.xml
<CustomField>
    <fullName>CQ_GJ_SQX_Parent_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>store the info about the child&apos;s parent</description>
    <label>Parent Info</label>
    <referenceTo>CQ_GJ_SQX_Parent_Object__c</referenceTo>
    <relationshipLabel>CQ GJ Child Objects</relationshipLabel>
    <relationshipName>CQ_GJ_Child_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CQ_GJ_SQX_Child_Object__c/fields/CQ_GJ_Upload_Marksheet__c.field-meta.xml
<CustomField>
    <fullName>CQ_GJ_Upload_Marksheet__c</fullName>
    <description>children will upload their mark sheets here</description>
    <label>Upload Marksheet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CQ_GJ_SQX_Parent_Object__c/CQ_GJ_SQX_Parent_Object__c.object-meta.xml
<CustomObject>
    <description>It will stores the info about the child&apos;s parent.</description>
    <label>CQ GJ Parent Object</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CQ GJ Parent Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CQ_GJ_SQX_Parent_Object__c/fields/CQ_GJ_Parent_Query__c.field-meta.xml
<CustomField>
    <fullName>CQ_GJ_Parent_Query__c</fullName>
    <label>Parent Query</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CQUI_GJ_Test_ChildObject.cls
@isTest
public class CQUI_GJ_Test_ChildObject {

 

    @isTest
    static void testPreventer() {
        System.runAs(FetchTestUser.createUserWithPermissionSet()){

            // Create parent record with status 'Draft'
            CQ_GJ_SQX_Parent_Object__c parent = new CQ_GJ_SQX_Parent_Object__c(
                Name = 'TestParent',
                CQ_GJ_Parent_Query__c = 'Draft'
            );
            insert parent;

            // Create child record and associate with the parent
            CQ_GJ_SQX_Child_Object__c child = new CQ_GJ_SQX_Child_Object__c(
                Name = 'TestChild',
                CQ_GJ_SQX_Parent_Info__c = parent.Id
            );
            insert child;

            // Update child when parent status is 'Draft' - should not throw error
            Test.startTest();
            child.Name = 'TestChildUpdated';
            Database.SaveResult result = Database.update(child, false);
            System.assert(result.isSuccess(), 'Error occurred while updating child with parent status as Draft');
            Test.stopTest();

            // Update parent status to 'Completed'
            parent.CQ_GJ_Parent_Query__c = 'Completed';
            update parent;

            // Update child now - an error is expected as the parent status is 'Completed'
            child.Name = 'TestChildUpdated2';
            Database.SaveResult result2 = Database.update(child, false);
            System.assert(!result2.isSuccess() && result2.getErrors()[0].getMessage().contains('Updation/Insertion of the child record at this stage is not allowed.'), 'Expected exception not thrown');
        }
    }

 

    @isTest
    static void testHandleBeforeDelete() {
        System.runAs(FetchTestUser.createUserWithPermissionSet()){

            // Create parent record with status 'Draft'
            CQ_GJ_SQX_Parent_Object__c parent = new CQ_GJ_SQX_Parent_Object__c(
                Name = 'TestParent',
                CQ_GJ_Parent_Query__c = 'Draft'
            );
            insert parent;

            // Create child record and associate with the parent
            CQ_GJ_SQX_Child_Object__c child = new CQ_GJ_SQX_Child_Object__c(
                Name = 'TestChild',
                CQ_GJ_SQX_Parent_Info__c = parent.Id
            );
            insert child;

            // Delete child when parent status is 'Draft' - should not throw error
            Test.startTest();
            Database.DeleteResult deleteResult = Database.delete(child, false);
            System.assert(deleteResult.isSuccess(), 'Error occurred while deleting child with parent status as Draft');
            Test.stopTest();

            // Insert child again for the next test scenario
             CQ_GJ_SQX_Child_Object__c child1 = new CQ_GJ_SQX_Child_Object__c(
                Name = 'TestChild12s',
                CQ_GJ_SQX_Parent_Info__c = parent.Id,
                 CQ_GJ_Upload_Marksheet__c = 'null0987654'
            );
            insert child1;

            // Update parent status to 'Completed'
            parent.CQ_GJ_Parent_Query__c = 'Completed';
            update parent;

            // Try deleting child - an error is expected as the parent status is 'Completed'
            Database.DeleteResult deleteResult2 = Database.delete(child1, false);
            System.assert(!deleteResult2.isSuccess(), 'Expected exception not thrown for deleting child with parent status as Completed');
        }
    }
}