force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateApexTriggerContainer.cls
public class CandidateApexTriggerContainer {

    // This method handles the sharing of Candidate__c records with users.
    // It takes a list of Candidate__c records as input and creates Candidate__Share records for sharing.
    public static void handle(List<Candidate__c> candList) {

        // Create a list to store the Candidate__Share records to be inserted.
        List<Candidate__Share> candShrs = new List<Candidate__Share>();

        for (Candidate__c cand : candList) {
            // Create a new Candidate__Share record for each Candidate__c record.
            Candidate__Share candidateShr = new Candidate__Share();
            CandidateShr.ParentId = cand.Id; // Set the ParentId to the Candidate__c record's Id.
            CandidateShr.UserOrGroupId = cand.User__c; // Set the UserOrGroupId for sharing.
            CandidateShr.AccessLevel = 'read'; // Set the access level, such as 'read'.

            // Set the RowCause to specify the reason for sharing (e.g., user__c).
            CandidateShr.RowCause = Schema.Candidate__Share.RowCause.user__c;

            // Add the Candidate__Share record to the list for insertion.
            candShrs.add(CandidateShr);
        }

        // Insert the Candidate__Share records into the database.
        // Use Database.insert with the allOrNone parameter set to false to handle partial successes.
        Database.SaveResult[] lsr = Database.insert(candShrs, false);
    }
}