force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internship__c/Internship__c.object-meta.xml
<CustomObject>
    <label>Internship</label>
    <nameField>
        <label>Internship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internship__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>for getting the notifications related applicants</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Internship__c/fields/Opennings__c.field-meta.xml
<CustomField>
    <fullName>Opennings__c</fullName>
    <label>Opennings Left</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Internship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
                <color>#009900</color>
                <default>true</default>
                <label>Opened</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <color>#FF0000</color>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Selected</fullName>
                <isActive>false</isActive>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Viewed</fullName>
                <isActive>false</isActive>
                <label>Viewed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internship_Application__c/Internship_Application__c.object-meta.xml
<CustomObject>
    <label>Internship Application</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Internship Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internship Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internship_Application__c/fields/CandEmail__c.field-meta.xml
<CustomField>
    <fullName>CandEmail__c</fullName>
    <defaultValue>$User.Email</defaultValue>
    <externalId>true</externalId>
    <label>CandEmail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Internship_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Internship Applications</relationshipLabel>
    <relationshipName>Internship_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internship_Application__c/fields/Internship__c.field-meta.xml
<CustomField>
    <fullName>Internship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internship</label>
    <referenceTo>Internship__c</referenceTo>
    <relationshipLabel>Internship Applications</relationshipLabel>
    <relationshipName>Internship_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internship_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Personal Interview</fullName>
                <isActive>false</isActive>
                <label>Personal Interview</label>
            </value>
            <value>
                <fullName>Review Resume</fullName>
                <isActive>false</isActive>
                <label>Review Resume</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InternshipApplicationTriggerContainer.cls
public class InternshipApplicationTriggerContainer {

    // This method sends an email alert for new internship applications
    public static void newInternshipAlert(List<Internship_Application__c> appList) {
        List<Messaging.Email> emailList = new List<Messaging.Email>();
        Id loggedInUserId = UserInfo.getUserId();

        for (Internship_Application__c app : appList) {
            // Query related internship application records
            List<Internship_Application__c> internshipApps = [SELECT Id, CandEmail__c, Name, Internship__r.Status__c, Candidate__r.Name, Internship__r.Email__c, Internship__r.Name FROM Internship_Application__c WHERE Id = :app.Id];

            String ownerEmails = null;
            String name = null;
            Id internshipId = null;
            String Status = null;
            String CandName = null;
            String candEmail = null;

            // Extract data from related records
            for (Internship_Application__c a : internshipApps) {
                ownerEmails = a.Internship__r.Email__c;
                name = a.Internship__r.Name;
                internshipId = a.Internship__r.Id;
                Status = a.Internship__r.Status__c;
                CandName = a.Candidate__r.Name;
                candEmail = a.CandEmail__c;
            }

            // Query to check for existing applications and status
            List<Internship_Application__c> aggregateResults = [SELECT Name FROM Internship_Application__c WHERE Internship__r.Id = :internshipId AND CandEmail__c = :candEmail];

            // Check conditions and send an email if necessary
            if (ownerEmails != null && aggregateResults.size() == 1 && Status == 'Opened') {
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setReplyTo(ownerEmails);
                email.setWhatId(app.Id);
                email.setToAddresses(new String[] { ownerEmails });
                email.setSubject('New Internship Application Found');
                email.setPlainTextBody('I hope this message finds you well. We are excited to inform you that a new internship application has been submitted for the ' + name + ' position.');
                emailList.add(email);
            } else {
                //check for duplicity
                if (aggregateResults.size() != 1) {
                    app.addError('You have already applied for the "' + name + '" position');
                } else if (Status != 'Opened') {
                    //checks if the status of openningStatus is closed, then stop hiring
                    app.addError('The hiring for this position is now "Closed"');
                }
            }
        }

        // Send the email messages (commented out)
        // Messaging.sendEmail(emailList);
    }

    // This method updates internship application statuses and sends emails accordingly
    public static void internshipApplicationStatusUpdater(List<Internship_Application__c> newList, Map<Id, Internship_Application__c> oldMaps) {
        List<Messaging.Email> emailList = new List<Messaging.Email>();

        for (Internship_Application__c app : newList) {
            Internship_Application__c oldApp = oldMaps.get(app.Id);

            if (app.Status__c == 'Hired' && oldApp.Status__c != 'Hired') {
                // Update the internship openings and send a "selected" email
                Internship_Application__c internshipApps = [SELECT Id, Name, Internship__r.Opennings__c, Internship__r.Email__c FROM Internship_Application__c WHERE Id = :app.Id LIMIT 1];
                if (internshipApps.Internship__r.Opennings__c > 0) {
                    internshipApps.Internship__r.Opennings__c -= 1;
                    update internshipApps.Internship__r;
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    email.setReplyTo(internshipApps.Internship__r.Email__c);
                    email.setWhatId(app.Id);
                    email.setToAddresses(new String[] { app.CandEmail__c });
                    email.setSubject('Internship Application Selected');
                    email.setPlainTextBody('Congratulations! We are pleased to inform you that your application for the ' + internshipApps.Name + ' position has been selected. We look forward to welcoming you to our organization.');
                    emailList.add(email);
                } else {
                    //if the related openning for any app is zero then 
                    app.addError('Openings are full for this internship');
                }
            } else if (oldApp.Status__c == 'Hired' && app.Status__c == 'Rejected') {
                // Update internship openings and send a "rejected" email
                Internship_Application__c internshipApps = [SELECT Id, Name, Internship__r.Opennings__c, Internship__r.Email__c FROM Internship_Application__c WHERE Id = :app.Id LIMIT 1];
                internshipApps.Internship__r.Opennings__c += 1;
                update internshipApps.Internship__r;
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setTargetObjectId(app.Id);
                email.setWhatId(app.Id);
                email.setToAddresses(new String[] { app.CandEmail__c });
                email.setSubject('Internship Application Rejected');
                email.setPlainTextBody('Thank you for applying. We could not process your application further. Please consider applying again in the future.');
                emailList.add(email);
            } else if (app.Status__c == 'Rejected') {
                // Send a "rejected" email
                Internship_Application__c internshipApps = [SELECT Id, Name, Internship__r.Email__c FROM Internship_Application__c WHERE Id = :app.Id LIMIT 1];
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setReplyTo(internshipApps.Internship__r.Email__c);
                email.setWhatId(app.Id);
                email.setToAddresses(new String[] { app.CandEmail__c });
                email.setSubject('Internship Application Rejected');
                email.setPlainTextBody('Thank you for applying. We could not process your application further. Please consider applying again in the future.');
                emailList.add(email);
            }
        }

        // Send the email messages (commented out)
        // Messaging.sendEmail(emailList);
    }

    // This method prevents the deletion of internship applications with a "Hired" status
    public static void preventDeleteInternship(List<Internship_Application__c> oldList) {
        for (Internship_Application__c app : oldList) {
            if (app.Status__c == 'Hired') {
                app.addError('Sorry, deleting this internship application is not allowed at this stage.');
            }
        }
    }
}