force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateApexSharingTest.cls
@isTest
public class CandidateApexSharingTest {

    static testMethod void testCandidateSharing() {
        //selecting the profiles to assign the testUser, and testUser should have the rights of the intern
         User testUser;
      String profileName = 'Intern';
         String query = 'SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1';
         List<Profile> internProfiles = Database.query(query);
         Date d = Date.today();

       {
         
     //creating the testUser  
      testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Username = 'gyanesh@mail.com',
            Email = 'gyanesh@mail.com',
            Alias = 'tuser',
            ProfileId = internProfiles[0].id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US');
        insert testUser;
       
    }
       
        //creating the testCandidate 

        Candidate__c testCandidate = new Candidate__c(
            Email__c = 'John@gmail.com',
            User__c=testUser.id
           );
        insert testCandidate;
      
        //assigning the apexSharing to that candidate
          
        List<Candidate__c> queriedStudents = [SELECT Id,  Email__c FROM Candidate__c WHERE User__c = :testUser.id LIMIT 1];
        System.debug(queriedStudents);

        Candidate__Share candidateShare = new Candidate__Share();
        candidateShare.ParentId = testCandidate.Id;
        candidateShare.UserOrGroupId = testUser.Id; 
        candidateShare.AccessLevel = 'read'; 
        candidateShare.RowCause = Schema.Candidate__Share.RowCause.user__c;

       
        //checking for the apexSharing

        
        List<Candidate__Share> candidateShares = [
            SELECT Id, ParentId, UserOrGroupId, AccessLevel, RowCause
            FROM Candidate__Share
            WHERE ParentId = :testCandidate.Id And UserOrGroupId=:testUser.id
        ];

        
        System.assertEquals(1, candidateShares.size());
        System.assertEquals(testUser.Id, candidateShares[0].UserOrGroupId);
        System.assertEquals('Read', candidateShares[0].AccessLevel);
        System.assertEquals(Schema.Candidate__Share.RowCause.user__c, candidateShares[0].RowCause);

    }
}