force-app/main/default/objects/Internship_Application__c/Internship_Application__c.object-meta.xml
<CustomObject>
    <label>Internship Application</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Internship Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internship Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internship_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Personal Interview</fullName>
                <isActive>false</isActive>
                <label>Personal Interview</label>
            </value>
            <value>
                <fullName>Review Resume</fullName>
                <isActive>false</isActive>
                <label>Review Resume</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InternshipApplicationApprovalController.cls
public with sharing class InternshipApplicationApprovalController {
    
    /**
     * @description approveRequest
     */
    @AuraEnabled
    public static String approveRejectRequest(String recordIdStr, String isApprove){
        try{
 
            String resultString = (isApprove=='Hired') ? 'Hired': 'Rejected';
            Internship_Application__c sta=New Internship_Application__c();
            sta.id=recordIdStr;
            sta.Status__c=resultString;
          
            update sta;
          
       
          
                return resultString;
           
        }
        catch(Exception e){ throw new AuraHandledException(e.getMessage()); }
    }
}